### ISSUE TITLE
dependency: go-whosonfirst-logs

### ISSUE THREAD

**Issue by missinglink** [whosonfirst/go-whosonfirst-pip#10]
the installation requires `go-whosonfirst-logs` but that repository is not available (to me)

``` bash
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/whosonfirst/go-whosonfirst-logs/'
package github.com/whosonfirst/go-whosonfirst-logs: exit status 128
```

other repos listed install without any issues

**Comment by thisisaaronland** [comment]
That was a typo that has been fixed. Also the README has been updated to focus on the handy Makefile that will do most of the heavy lifting for you.

https://github.com/whosonfirst/go-whosonfirst-pip#set-up
