### ISSUE TITLE
Non-reproducible invalid responses

### ISSUE THREAD

**Issue by trescube** [whosonfirst/go-whosonfirst-pip#15]
While making programmatic requests, I sometimes (very rarely, maybe 2-4 out of 100k requests) get `null`s in response array.  Here's an example request:

`http://localhost:8080/?latitude=40.005692&longitude=-76.366943`

Requests thru the browser respond with:

```
[{
    Id: 102081377,
    Name: "Lancaster",
    Placetype: "county",
    Offset: -1
}, {
    Id: 85688481,
    Name: "Pennsylvania",
    Placetype: "region",
    Offset: -1
}, {
    Id: 85633793,
    Name: "United States",
    Placetype: "country",
    Offset: -1
}, {
    Id: 404485323,
    Name: "Manor",
    Placetype: "localadmin",
    Offset: -1
}, {
    Id: 85856227,
    Name: "West Ridge",
    Placetype: "neighbourhood",
    Offset: -1
}]
```

Whereas the programmatic response will look like:

```
[null, {
    "Id": 102081377,
    "Name": "Lancaster",
    "Placetype": "county",
    "Offset": -1
}, {
    "Id": 85688481,
    "Name": "Pennsylvania",
    "Placetype": "region",
    "Offset": -1
}, {
    "Id": 85633793,
    "Name": "United States",
    "Placetype": "country",
    "Offset": -1
}, {
    "Id": 85856227,
    "Name": "West Ridge",
    "Placetype": "neighbourhood",
    "Offset": -1
}]
```

Comparing the two responses, it appears that the `localadmin` PlaceType array entry is missing.  On another request, the `region` PlaceType array entry is missing but available when requested thru the browser, so it doesn't seem to be confined to 1 place type.

**Comment by thisisaaronland** [comment]
I am curious whether this is a node thing, mostly because Go is so strongly typed I am just not sure how it could get as far as to return a null object. Specifically, the response is being marshaled and sent back here:

https://github.com/whosonfirst/go-whosonfirst-pip/blob/master/cmd/wof-pip-server.go#L154-L169

And the signature for the data being returned it here:

https://github.com/whosonfirst/go-whosonfirst-pip/blob/master/pip.go#L351

Looking at the debug output I am not sure how Go would even allow a `null` value unless it's possible to include `nil` (Go's equivalent of null) in `[]*geojson.WOFSpatial`...

As in:

```
# test.go

type Foo struct {
     bar string
}

func main () {

     stuff := make([]Foo, 0)

     stuff = append(stuff, Foo{"hello"})
     fmt.Println(stuff)

     stuff = append(stuff, Foo{"world"})
     fmt.Println(stuff)

     stuff = append(stuff, nil)
     fmt.Println(stuff)
}

$> go build test.go
./test.go:21: cannot use nil as type Foo in append
```

**Comment by thisisaaronland** [comment]
For good time... pointers. Always pointers...

```
$> cat test.go
package main

import (
       "fmt"
       "encoding/json"
)

type Foo struct {
     Bar string
}

func main() {

    test := make([]*Foo, 0)

    test = append(test, &Foo{"hello"})
    fmt.Println(test)

    test = append(test, &Foo{"world"})
    fmt.Println(test)

    test = append(test, nil)
    fmt.Println(test)

    str, _ := json.Marshal(test)
    fmt.Printf("%s\n", str)
}

$> go run test.go
[0xc820074290]
[0xc820074290 0xc8200742c0]
[0xc820074290 0xc8200742c0 <nil>]
[{"Bar":"hello"},{"Bar":"world"},null]
```

I am sure there is some well-reasoned theory document explaining why computers wouldn't work _at all_ if this weren't the expected behaviour but... kjhkhjjkfdjhfsdhfsdhjkhjksfdjkhfnmnmkjhsdjhsdflhgjcfsgf.

Anyway, I can add a band-aid in the morning to filter out `nil` values and then figure out how and why they are being added in the first place...

**Comment by thisisaaronland** [comment]
It's live live-blogging for debugging. Stepping through the code so far we start with this:

```
intersects, duration := p.GetIntersectsByLatLon(lat, lon)
inflated, duration := p.InflateSpatialResults(intersects)
```

https://github.com/whosonfirst/go-whosonfirst-pip/blob/master/pip.go#L328-L334

It is unlikely to be either of these functions `intersects` is an array of `rtreego.Spatial` interfaces that are iterated as cast as `*geojson.WOFSpatial` structs and you can't do that with `nil` values:

```
package main

import (
       "fmt"
       "encoding/json"
)

type Baz interface {
     WTF() string
}

type Foo struct {
     Bar string
}

func (f *Foo) WTF() string {
     return f.Bar
}

func main() {

    test := make([]interface{}, 0)

    test = append(test, &Foo{Bar:"hello"})
    fmt.Println(test)

    test = append(test, &Foo{Bar:"world"})
    fmt.Println(test)

    test = append(test, nil)
    fmt.Println(test)

    for i, f := range test {

    fmt.Printf("%d %T\n", i, f)

    if f == nil {
       fmt.Printf("%d is NIL\n", i)
    }

    b := f.(Baz)
    fmt.Printf("b is %T (%v)\n", b, b)
    fmt.Println("WTF says", b.WTF())
    }

    str, _ := json.Marshal(test)
    fmt.Printf("%s\n", str)
}

go run ./test.go
[0xc82000a250]
[0xc82000a250 0xc82000a290]
[0xc82000a250 0xc82000a290 <nil>]
0 *main.Foo
b is *main.Foo (&{hello})
WTF says hello
1 *main.Foo
b is *main.Foo (&{world})
WTF says world
2 <nil>
2 is NIL
panic: interface conversion: interface is nil, not main.Baz

goroutine 1 [running]:
main.main()
    test.go:41 +0x80d
exit status 2

```

The result is the same if you try to cast `b := f.(Baz)` ...

**Comment by thisisaaronland** [comment]
@trescube can you rebuild the server using the `omgwtfnil` branch and run the server with the `-verbose` flag and writing metrics to disk.

The branch doesn't actually _fix_ anything but checks the results for nil values at each step of the PIP process. Like this:

```
curl 'http://localhost:8080/?latitude=40.005692&longitude=-76.366943'
[{"Id":85688481,"Name":"Pennsylvania","Placetype":"region","Offset":-1}]

wof-pip-server] 13:19:48.321033 [status] indexed 4699 records in 15.997 seconds
[wof-pip-server] 13:19:48.321038 [status] indexed region: 4699
[wof-pip-server] 13:20:17.359901 [info] GetIntersectsByLatLon check: false
[wof-pip-server] 13:20:17.359918 [info] InflateSpatialResults check: false
[wof-pip-server] 13:20:17.359923 [info] FilterByPlacetypes check: false
[wof-pip-server] 13:20:17.360119 [info] EnsureContained check: false
[wof-pip-server] 13:20:17.360127 [info] GetByLatLonForPlacetype check: false
```

If the final check returns true then the lat,lon,placetype will also be logged as a warning.

https://github.com/whosonfirst/go-whosonfirst-pip/compare/omgwtfnil

**Comment by trescube** [comment]
I ran the `omgwtfnil` branch with `-verbose`.  Output is attached.  
[output.TXT.gz](https://github.com/whosonfirst/go-whosonfirst-pip/files/86012/output.TXT.gz)

The input in this case was for lat/lon `40.196917,-76.20393`.  Here's the response it did get:

```
[{
    "Id": 102081377,
    "Name": "Lancaster",
    "Placetype": "county",
    "Offset": -1
}, {
    "Id": 85688481,
    "Name": "Pennsylvania",
    "Placetype": "region",
    "Offset": -1
}, {
    "Id": 85830575,
    "Name": "Lincoln",
    "Placetype": "neighbourhood",
    "Offset": -1
}, {
    "Id": 404487079,
    "Name": "Ephrata",
    "Placetype": "localadmin",
    "Offset": -1
}, {
    "Id": 101718645,
    "Name": "Ephrata",
    "Placetype": "locality",
    "Offset": -1
}, null]
```

**Comment by thisisaaronland** [comment]
So, the thing is that according to your debug out none of the arrays contain a `nil` value:

```
grep true ./output.TXT | wc -l
       0
```

Does this only happen for that lat,lon ? Does it only happen for lat,lon pairs in Lancester? What are you using to query the (PIP) server and how? Have you enabled metrics ?

**Comment by trescube** [comment]
It's not reproducible, if I were to run that lat/lon again, there will most likely not be a null in the output.  Sometimes it doesn't happen at all, but I can try another county.  

My node code is just making requests like: `http://localhost:8080/?latitude=40.158305&longitude=-76.199835`

I have not enabled metrics but I'm looking into it now.

**Comment by thisisaaronland** [comment]
I can think of two possible reasons, off the top of head:

1) There is a bug in the underlying Rtree implementation – one way to test that would be to see if the problem can be reproduced with:

https://github.com/whosonfirst/go-whosonfirst-rtree/blob/master/cmd/wof-rtree-pip.go

2) There is a bug in sync/waitgroup code to do raycasting:

https://github.com/whosonfirst/go-whosonfirst-pip/blob/master/pip.go#L419-L512

At a glance it looks fine; the only thing that stands out is not calling `wg.Add` atomically but since the total number of jobs scheduled would be the same (doing `wg.Add(len(list))`) it's hard to see why that would be the problem.

**Comment by thisisaaronland** [comment]
```
Stephen Hess [13:59] 
good news!  ran thru the entire lancaster file twice and no crashes or nulls
​[14:00] 
however, there are still some conflicting responses for identical lat/lon inputs
[14:00] 
15 differences over 212,732 inputs, to be exact
​[14:03] 
scratch that, turns out there are some inputs that return 2 neighborhoods and the order got flipped in my comparisons, so they’re not actually differences
​[14:03] 
so i’d say that all those issues can be closed
```
