### ISSUE TITLE
Responses are not identical between runs

### ISSUE THREAD

**Issue by trescube** [whosonfirst/go-whosonfirst-pip#18]
I'm encountering issues between requests for identical lat/lon's where the responses are not identical. 
 An example lat/lon is `40.158305,-76.199835`.  Node behind the scenes is issuing the request:

`http://localhost:8080/?latitude=40.158305&longitude=-76.199835`

The first run resulted in this:

```
[{
    "Id": 85633793,
    "Name": "United States",
    "Placetype": "country",
    "Offset": -1
}, {
    "Id": 102081377,
    "Name": "Lancaster",
    "Placetype": "county",
    "Offset": -1
}, {
    "Id": 404486947,
    "Name": "Akron",
    "Placetype": "localadmin",
    "Offset": -1
}, {
    "Id": 101718617,
    "Name": "Akron",
    "Placetype": "locality",
    "Offset": -1
}, {
    "Id": 85830575,
    "Name": "Lincoln",
    "Placetype": "neighbourhood",
    "Offset": -1
}*, {
    "Id": 85688481,
    "Name": "Pennsylvania",
    "Placetype": "region",
    "Offset": -1
}*]
```

Here's the output from the second run:

```
[{
    "Id": 85633793,
    "Name": "United States",
    "Placetype": "country",
    "Offset": -1
}, {
    "Id": 102081377,
    "Name": "Lancaster",
    "Placetype": "county",
    "Offset": -1
}, {
    "Id": 404486947,
    "Name": "Akron",
    "Placetype": "localadmin",
    "Offset": -1
}, {
    "Id": 101718617,
    "Name": "Akron",
    "Placetype": "locality",
    "Offset": -1
}, {
    "Id": 85830575,
    "Name": "Lincoln",
    "Placetype": "neighbourhood",
    "Offset": -1
}]
```

If my markdown doesn't work, the latter is missing the `region` Placetype.  

Here's another instance, this time requesting `40.158814,-76.199537`.  First response:

```
[{
    "Id": 85633793,
    "Name": "United States",
    "Placetype": "country",
    "Offset": -1
}, {
    "Id": 102081377,
    "Name": "Lancaster",
    "Placetype": "county",
    "Offset": -1
}, {
    "Id": 404486947,
    "Name": "Akron",
    "Placetype": "localadmin",
    "Offset": -1
}, {
    "Id": 101718617,
    "Name": "Akron",
    "Placetype": "locality",
    "Offset": -1
}, {
    "Id": 85830575,
    "Name": "Lincoln",
    "Placetype": "neighbourhood",
    "Offset": -1
}, {
    "Id": 85688481,
    "Name": "Pennsylvania",
    "Placetype": "region",
    "Offset": -1
}]
```

Second response:

```
[{
    "Id": 85633793,
    "Name": "United States",
    "Placetype": "country",
    "Offset": -1
}, {
    "Id": 102081377,
    "Name": "Lancaster",
    "Placetype": "county",
    "Offset": -1
}, {
    "Id": 101718617,
    "Name": "Akron",
    "Placetype": "locality",
    "Offset": -1
}, {
    "Id": 85830575,
    "Name": "Lincoln",
    "Placetype": "neighbourhood",
    "Offset": -1
}, {
    "Id": 85688481,
    "Name": "Pennsylvania",
    "Placetype": "region",
    "Offset": -1
}]
```

In this case, the second response is missing the `localadmin` Placetype entry.  

Unfortunately, this is not reproducible.  Subsequent runs will produce identical outputs for these lat/lon pairs.  

Command used to start the server:

`./bin/wof-pip-server -data ~/git/whosonfirst/whosonfirst-data/data -strict ~/git/whosonfirst/whosonfirst-data/meta/wof-country-latest.csv ~/git/whosonfirst/whosonfirst-data/meta/wof-locality-latest.csv ~/git/whosonfirst/whosonfirst-data/meta/wof-county-latest.csv ~/git/whosonfirst/whosonfirst-data/meta/wof-region-latest.csv ~/git/whosonfirst/whosonfirst-data/meta/wof-neighbourhood-latest.csv ~/git/whosonfirst/whosonfirst-data/meta/wof-localadmin-latest.csv`

**Comment by trescube** [comment]
I loaded just `locality` and `localadmin` and am still getting data differences between runs.  For `39.994299,-76.245358`, here's the 1st run:

```
[{
    "Id": 404485553,
    "Name": "West Lampeter",
    "Placetype": "localadmin",
    "Offset": -1
}, {
    "Id": 101720433,
    "Name": "Lampeter",
    "Placetype": "locality",
    "Offset": -1
}]
```

and the 2nd run:

```
[{
    "Id": 101720433,
    "Name": "Lampeter",
    "Placetype": "locality",
    "Offset": -1
}]
```

In this case, the 2nd run is missing the `localadmin` placetype.

Command used to start the server:

`./bin/wof-pip-server -data ~/git/whosonfirst/whosonfirst-data/data -strict ~/git/whosonfirst/whosonfirst-data/meta/wof-locality-latest.csv ~/git/whosonfirst/whosonfirst-data/meta/wof-localadmin-latest.csv`

**Comment by thisisaaronland** [comment]
When you say "run" do you mean HTTP request or something else ?

Also, can you send me the list of files and flags you're starting the
server with.

**Comment by trescube** [comment]
I have node code that iterates the Lancaster County, PA file from OpenAddresses doing PiP lookups on the lat/lon pairs.  The node code does http requests like `http://localhost:8080/?latitude=40.158305&longitude=-76.199835`.  The reason I use the term 'run' is because it's not reproducible so I'm issuing 25k requests.  

I've updated the previous comments with commands used to start the server that led to those issues.

**Comment by trescube** [comment]
Still having issues with code containing mutex.  The lat/lon is `40.093477,-76.411876`.  The first run's result was:

```
[{
    "Id": 101720455,
    "Name": "Landisville",
    "Placetype": "locality",
    "Offset": -1
}]
```

Whereas the second run's result was:

```
[{
    "Id": 404487069,
    "Name": "East Hempfield",
    "Placetype": "localadmin",
    "Offset": -1
}, {
    "Id": 101720455,
    "Name": "Landisville",
    "Placetype": "locality",
    "Offset": -1
}]
```

Only locality and localadmin data was loaded.

**Comment by thisisaaronland** [comment]
```
Stephen Hess [13:59] 
good news!  ran thru the entire lancaster file twice and no crashes or nulls
​[14:00] 
however, there are still some conflicting responses for identical lat/lon inputs
[14:00] 
15 differences over 212,732 inputs, to be exact
​[14:03] 
scratch that, turns out there are some inputs that return 2 neighborhoods and the order got flipped in my comparisons, so they’re not actually differences
​[14:03] 
so i’d say that all those issues can be closed
```
