### ISSUE TITLE
2 character regions and country codes

### ISSUE THREAD

**Issue by trescube** [whosonfirst/go-whosonfirst-pip#20]
Would it be possible to expose 2 character region codes for US and 2 character country codes?  Pelias uses that data for it's imports and looking it up via spelunker would add a significant performance penalty.

**Comment by thisisaaronland** [comment]
The short answer is: Yes, we can do anything we need to.

The longer answer is: I'd like to have a think about how we do it.

Specifically one of the design goals of the the pip server is to be use-able with any old GeoJSON blob and so it's pretty conservative/limited about the properties [1] it returns. I have a couple idea but I'd like to think through them a bit more...

[1] https://github.com/whosonfirst/go-whosonfirst-geojson/blob/master/geojson.go#L26-L35
