### ISSUE TITLE
Add support for (encoded) polylines

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/go-whosonfirst-pip#9]
Maybe? See also:
- https://github.com/whosonfirst/py-mapzen-routing/blob/master/scripts/wof-describe-route
- https://developers.google.com/maps/documentation/utilities/polylinealgorithm
- https://github.com/areusch/gmaps

**Comment by riordan** [comment]
Would this also apply to polygons (i.e. reverse geocoding an area of interest or zip code that spans several towns)?

**Comment by thisisaaronland** [comment]
https://github.com/whosonfirst/go-whosonfirst-pip/commit/540b25971ece53c20f0555e86255339c1f15fae9

**Comment by riordan** [comment]
![YAY](http://bukk.it/omgyay.gif)

Immediately I'm interested in seeing where the [Trans-Siberian Railway](http://www.openstreetmap.org/relation/2128634#map=3/51.45/86.31) (link full of firefox tears) falls into.

**Comment by thisisaaronland** [comment]
@riordan see also: https://github.com/whosonfirst/osm-tools/blob/master/bin/rel2coords.py

This is still wet-paint and I am waiting for it to complete its first run but it will generate a polyline at the end. Note the lack of CLI flags and all the usual yadda yadda yadda...

**Comment by thisisaaronland** [comment]
Test (load, etc.) with Valhalla routes:

https://github.com/valhalla/tools/tree/master/test_requests
